version: '3.2'

services:

  upserver-postgres:
    container_name: upserver-postgres
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /data/pgdata
    volumes:
      - upserver-postgres:/data/pgdata
    ports:
      - "55432:5432"
    expose:
      - "5432"
    restart: unless-stopped
    networks:
      - upserver  

  upserver-rabbitmq:
    container_name: upserver-rabbitmq
    image: 'rabbitmq:3.11.4-management'
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
      RABBITMQ_DEFAULT_VHOST: vhost
    ports:
      - '55672:5672'
      - '51567:15672'
    expose:
      - "5672"    
    volumes:
      - upserver-rabbitmq:/var/lib/rabbitmq/mnesia/
    restart: unless-stopped
    networks:
      - upserver

  upserver-interface:
    container_name: upserver-interface
    build: 
      context: ./interface/
      dockerfile: Dockerfile 
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      DEBUG: ${DEBUG}
      SECRET_KEY: ${SECRET_KEY} 
      ADMIN_USER: ${ADMIN_USER}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD} 
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}        
    restart: unless-stopped 
    depends_on: 
      - upserver-postgres 
      - upserver-rabbitmq 
    ports:
      - 12345:12345
    networks:
      - upserver  

  upserver-monitoring:
    container_name: upserver-monitoring
    build: 
      context: ./monitoring/
      dockerfile: Dockerfile  
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      DEBUG: ${DEBUG}  
    restart: unless-stopped 
    depends_on: 
      - upserver-postgres
    networks:
      - upserver  

networks:
  upserver:
    driver: bridge
  
volumes:
  upserver-postgres:
  upserver-rabbitmq:
  
