version: '3.2'

services:
  upserver-interface:
    environment:
      DEBUG: 1
    build: 
      target: dev
    volumes:
      - ./interface:/interface

  upserver-alerts: 
    environment:
      DEBUG: 1
    build: 
      target: dev
    volumes:
      - ./alerts:/alerts