# Generated by Django 4.1.1 on 2022-11-30 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SimplePrintCatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.JSONField()),
                ('tag', models.CharField(max_length=255)),
                ('queue', models.CharField(max_length=255)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClickHouseLogger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=255, null=True)),
                ('asctime', models.DateTimeField(auto_now_add=True)),
                ('exc_info', models.CharField(blank=True, max_length=255, null=True)),
                ('exc_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.CharField(blank=True, max_length=255, null=True)),
                ('user_id', models.PositiveIntegerField(default=22)),
                ('request_extra', models.CharField(blank=True, max_length=255, null=True)),
                ('site', models.CharField(blank=True, max_length=255, null=True)),
                ('scheme', models.CharField(blank=True, max_length=255, null=True)),
                ('body', models.CharField(blank=True, max_length=255, null=True)),
                ('path', models.CharField(blank=True, max_length=255, null=True)),
                ('method', models.CharField(blank=True, max_length=255, null=True)),
                ('GET', models.CharField(blank=True, max_length=255, null=True)),
                ('POST', models.CharField(blank=True, max_length=255, null=True)),
                ('headers', models.CharField(blank=True, max_length=255, null=True)),
                ('args', models.CharField(blank=True, max_length=255, null=True)),
                ('kwargs', models.CharField(blank=True, max_length=255, null=True)),
                ('pathname', models.CharField(blank=True, max_length=255, null=True)),
                ('funcName', models.CharField(blank=True, max_length=255, null=True)),
                ('lineno', models.PositiveIntegerField(default=22)),
                ('message', models.CharField(blank=True, max_length=255, null=True)),
                ('exc_text', models.CharField(blank=True, max_length=255, null=True)),
                ('created', models.FloatField(blank=True, null=True)),
                ('filename', models.CharField(blank=True, max_length=255, null=True)),
                ('levelname', models.CharField(blank=True, max_length=255, null=True)),
                ('levelno', models.CharField(blank=True, max_length=255, null=True)),
                ('module', models.CharField(blank=True, max_length=255, null=True)),
                ('msecs', models.FloatField(default=22)),
                ('msg', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('process', models.CharField(blank=True, max_length=255, null=True)),
                ('processName', models.CharField(blank=True, max_length=255, null=True)),
                ('relativeCreated', models.CharField(blank=True, max_length=255, null=True)),
                ('stack_info', models.CharField(blank=True, max_length=255, null=True)),
                ('thread', models.CharField(blank=True, max_length=255, null=True)),
                ('threadName', models.CharField(blank=True, max_length=255, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClickHouseCaptureException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=255, null=True)),
                ('asctime', models.DateTimeField(auto_now_add=True)),
                ('exc_info', models.CharField(blank=True, max_length=255, null=True)),
                ('exc_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('message', models.CharField(blank=True, max_length=255, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
