# Generated by Django 4.1.1 on 2022-12-05 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clickhouselogger',
            name='request_extra',
            field=models.TextField(blank=True, null=True),
        ),
    ]
