# Generated by Django 4.1.1 on 2022-12-08 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_alter_clickhouselogger_request_extra'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clickhousecaptureexception',
            options={'verbose_name': 'Captured exceptions', 'verbose_name_plural': 'Captured exceptions'},
        ),
        migrations.AlterModelOptions(
            name='clickhouselogger',
            options={'verbose_name': 'Django Errors', 'verbose_name_plural': 'Django Errors'},
        ),
        migrations.AlterModelOptions(
            name='simpleprintcatch',
            options={'verbose_name': 'Get alerts', 'verbose_name_plural': 'Get alerts'},
        ),
        migrations.AlterField(
            model_name='clickhouselogger',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
