# Generated by Django 4.1.7 on 2023-03-16 08:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("log_collector", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="collectorexception",
            name="fn_data",
            field=models.TextField(blank=True, null=True),
        ),
    ]
