# Generated by Django 4.1.7 on 2023-03-20 17:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("log_collector", "0002_collectorexception_fn_data"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="anylogger",
            options={},
        ),
        migrations.AlterModelOptions(
            name="collectorexception",
            options={},
        ),
        migrations.AlterModelOptions(
            name="djangoexception",
            options={},
        ),
        migrations.AlterModelOptions(
            name="djangologger",
            options={},
        ),
        migrations.AlterModelOptions(
            name="nginxlogger",
            options={},
        ),
        migrations.AlterField(
            model_name="djangoexception",
            name="exc_info",
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name="djangoexception",
            name="message",
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
