# Generated by Django 4.1.7 on 2023-05-02 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_collector', '0003_alter_anylogger_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djangoexception',
            name='exc_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='djangologger',
            name='user_id',
            field=models.PositiveIntegerField(blank=True, default=22, null=True),
        ),
    ]
