# Generated by Django 4.1.7 on 2023-07-11 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log_collector', '0005_cronscheduler_remove_nginxlogger_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nginxlogger',
            old_name='status_code',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='nginxlogger',
            name='host',
        ),
        migrations.RemoveField(
            model_name='nginxlogger',
            name='http_referrer',
        ),
        migrations.RemoveField(
            model_name='nginxlogger',
            name='http_x_forwarded_for',
        ),
        migrations.RemoveField(
            model_name='nginxlogger',
            name='request_id',
        ),
        migrations.RemoveField(
            model_name='nginxlogger',
            name='request_length',
        ),
        migrations.RemoveField(
            model_name='nginxlogger',
            name='request_time',
        ),
        migrations.RemoveField(
            model_name='nginxlogger',
            name='request_timestamp',
        ),
        migrations.RemoveField(
            model_name='nginxlogger',
            name='scheme',
        ),
        migrations.RemoveField(
            model_name='nginxlogger',
            name='server_addr',
        ),
        migrations.RemoveField(
            model_name='nginxlogger',
            name='upstream_addr',
        ),
        migrations.RemoveField(
            model_name='nginxlogger',
            name='upstream_connect_time',
        ),
        migrations.RemoveField(
            model_name='nginxlogger',
            name='upstream_header_time',
        ),
        migrations.RemoveField(
            model_name='nginxlogger',
            name='upstream_response_time',
        ),
    ]
