# Generated by Django 4.1.7 on 2023-07-18 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_collector', '0007_nginxlogger_http_referer_nginxlogger_time_local'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nginxlogger',
            name='http_referer',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='nginxlogger',
            name='remote_addr',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='nginxlogger',
            name='request_uri',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
