# Generated by Django 4.1.7 on 2023-08-05 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_collector', '0008_alter_nginxlogger_http_referer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskScheduler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=500)),
                ('task_active', models.BooleanField(default=False)),
                ('task_completed', models.BooleanField(default=False)),
                ('task_time', models.FloatField(blank=True, null=True)),
                ('task_stdout', models.TextField(blank=True, null=True)),
                ('task_error_tb', models.TextField(blank=True, null=True)),
                ('task_cron_time', models.CharField(blank=True, max_length=100, null=True)),
                ('task_memory', models.TextField(blank=True, null=True)),
                ('task_query_count', models.IntegerField(blank=True, null=True)),
                ('task_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='CronScheduler',
        ),
    ]
