# Generated by Django 4.1.7 on 2023-08-15 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_collector', '0010_alter_anylogger_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djangologger',
            name='user_id',
            field=models.IntegerField(blank=True, default=22, null=True),
        ),
    ]
