# Generated by Django 4.1.1 on 2022-10-01 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monitoractivity',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='restoreactivity',
            options={'ordering': ['-id']},
        ),
        migrations.RemoveField(
            model_name='monitor',
            name='last_monitoring_date',
        ),
    ]
