# Generated by Django 4.1.1 on 2022-10-01 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_alter_monitoractivity_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='restore_hops',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
