# Generated by Django 4.1.1 on 2022-10-01 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_monitor_restore_hops'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitor',
            name='port',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='restore_hops',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='su_port',
            field=models.PositiveIntegerField(default=22),
        ),
    ]
