# Generated by Django 4.1.1 on 2022-10-01 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0004_alter_monitor_port_alter_monitor_restore_hops_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restoreactivity',
            name='exit_status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
