# Generated by Django 4.1.1 on 2022-10-02 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0005_restoreactivity_exit_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoractivity',
            name='server_available',
            field=models.BooleanField(default=True),
        ),
    ]
